### ISSUE TITLE
meta tags and stuff

### ISSUE THREAD

**Issue by Haroenv** [gin-fizz/pollistics#70]
- [x] home page should have just "Pollistics" as title
- [ ] add Facebook/twitter tags
- [x] add the favicon (already made in style.pollistics.com, no need to duplicate, only make all kinds of png versions)
- [x] make description of polls less spoiler-ey and less nerdy
